export const CartActionTypes = {
    TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
    TOGGLE_HIDDEN_IMAGE: 'TOGGLE_HIDDEN_IMAGE',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    CLEAR_CART: 'CLEAR_CART'

}

