export const CartActionTypes = {
    TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
    TOGGLE_HIDDEN_IMAGE: 'TOGGLE_HIDDEN_IMAGE',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    TO_ITEM_DETAILS: 'TO_ITEM_DETAILS',
    DELETE_ITEM: 'DELETE_ITEM',
    

}

